language: java
jdk: oraclejdk7
sudo: false
install:
- mvn --version
before_script:
- export DISPLAY=:99
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- cd info.limpet.targetplatforms
- mvn clean install
- cd ..
- mvn clean verify -U -B -fae
- bash ./deploy_ghpages.sh
env:
  global:
  - GH_REF: github.com/pecko/limpet-release.git
  - secure: MOvtYKw+qvAiELhYhDKMNfunnTJ4rPN+FLCtmvzGpXk9tIehrzvGOnzFeuUcwC99EJ+aHh4vmMKEazKY+kCN7+TzrHTypoY42GF2WkKbkvQg9DDkdBEM7NDqbNijO0TTOExTTC+azHW9UJOMsfM5XhbRnOTJNCA44bEiUhYBnlBGHXU9lrx9f7UbLzEOm5bPKR9hevoGWlhIQvKeh3dKOpHWxGJedAL/3ZnR+Wnh5vPhqjx8V+e+k77H0pEAoVBjvbL1Pc6+q+2VPhxOzw0SE5JDQTP47eYGzNuoknHkdFfwSIeNHv2Dtel8ge9VwGtbvWtwhg0z4e6vVe/k5DBweTCutSbTVwKZoNwTtbdQM0+c/gIhhXLaBLbfCWheAvnNqhge00G0k1+jC/QGNlsvok337LGvbJBE1WFzCpFnWDrRPKZhQffY9la461bImLzUJbac0GvVjwLhTblbGV7jnXZ2qB0tyqENBenA+ufffQzxk5bqDYvibhxeaQrE/S1yRosbnBa9wveKRLnRFj/3HMlUnkwJf9uBs94K7l18TWVSk6Uvd1HN7C0DhP8nTkkpZYn82u6tJlFso7A7wBxfcvcapOrXlgCPfJoGkjjq+eURZiYKO40yGmppJyy+JLc3BZQTTuo/INe05hKSv6NLIkgpEIsTl8WDWjAqwzRMGNE=
